# GET http://localhost:3000/

POST http://localhost:3000/api/auth/signup
content-type: application/json

{ "username": "adaham",
 "email": "hghhh", 
 "password": "ghhh", 
 "account_type":  "hjhj",
  "phone_number" : 578888
}